# Generated by Django 2.2.5 on 2019-09-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_postd_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='postd_by',
            new_name='posted_by',
        ),
    ]
